//! Session lifecycle: window start/settle, shutdown (awaited
//! cancel-all on SIGINT/SIGTERM), and deterministic journal replay.

use super::*;

impl Engine {
    /// Resolves on Ctrl-C (SIGINT) or SIGTERM — both mean "stop the process".
    pub(super) async fn shutdown_signal() {
        #[cfg(unix)]
        {
            let mut term =
                tokio::signal::unix::signal(tokio::signal::unix::SignalKind::terminate())
                    .expect("install SIGTERM handler");
            tokio::select! {
                _ = tokio::signal::ctrl_c() => {}
                _ = term.recv() => {}
            }
        }
        #[cfg(not(unix))]
        {
            let _ = tokio::signal::ctrl_c().await;
        }
    }

    /// Cancel everything and WAIT for the live cancel to complete — used on
    /// process stop, where a fire-and-forget task would be killed mid-flight.
    pub(super) async fn cancel_all_and_wait(&mut self) {
        let _ = self.oms.cancel_all();
        if self.cfg.general.dry_run {
            self.exec_dry.cancel_all();
            return;
        }
        #[cfg(feature = "live")]
        if let Some(exec) = &self.exec_live {
            match exec.cancel_all().await {
                Ok(()) => tracing::info!("all orders cancelled at the exchange"),
                Err(e) => tracing::error!("shutdown cancel_all FAILED: {e} — orders may rest until heartbeat timeout"),
            }
        }
    }

    pub(super) fn settle_window(&mut self, m: &MarketInfo) {
        // Cancel everything, then write the PnL line.
        self.execute(vec![Action::CancelAll]);
        let yes = self.positions.get(&m.token_yes).cloned().unwrap_or_default();
        let no = self.positions.get(&m.token_no).cloned().unwrap_or_default();
        let summary = pnl_log::WindowSummary {
            slug: &m.slug,
            end_date_iso: &m.end_date_iso,
            symbol: &self.cfg.general.symbol,
            spot_open: (self.fair.open_price() > 0.0).then(|| self.fair.open_price()),
            spot_close: self.fair.latest_price(),
            sides: vec![("YES", &yes), ("NO", &no)],
        };
        let line = pnl_log::format_line(
            &chrono::Local::now().format("%Y-%m-%d %H:%M:%S").to_string(),
            &summary,
        );
        match pnl_log::append(&self.cfg.general.pnl_log_dir, &self.cfg.general.symbol, &line) {
            Ok(p) => tracing::info!("PnL appended to {}", p.display()),
            Err(e) => tracing::warn!("PnL log failed: {e}"),
        }
        if self.lat.dispatch.count() > 0 {
            tracing::info!("window {}", self.lat.report());
            self.lat.reset();
        }
        if let Some(j) = self.journal.as_mut() {
            j.flush();
        }
    }

    pub(super) fn start_window(&mut self, m: MarketInfo) {
        tracing::info!(
            "active market: {} end={} (yes={}… no={}…)",
            m.slug,
            m.end_date_iso,
            &m.token_yes[..m.token_yes.len().min(8)],
            &m.token_no[..m.token_no.len().min(8)]
        );
        self.positions.clear();
        self.tops.clear();
        self.oms.reset_window();
        self.throttle.reset();
        self.exec_dry.cancel_all();
        self.halted = false;
        match &mut self.strat {
            Strategy::Taker(t) => t.on_window_start(),
            Strategy::Maker(mk) => mk.on_window_start(),
        }
        self.market = Some(m);
    }

    /// Deterministic replay: feed a recorded journal through the engine
    /// instead of live sockets. Requires dry-run (fills are regenerated by
    /// the simulator from Book events; recorded UserTrade/OrderAck events
    /// are skipped). The virtual clock follows journal timestamps, and the
    /// 100ms/1s timers are synthesized between events — same events + same
    /// clock ⇒ same decisions, so one binary is both trader and backtester.
    pub fn replay(mut self, path: &std::path::Path) -> Result<(), String> {
        assert!(self.cfg.general.dry_run, "replay requires dry-run mode");
        self.journal = None; // never re-record a replay
        let records = crate::journal::read(path)?;
        let mut next_fast: Option<f64> = None;
        let mut next_sec: Option<f64> = None;
        let mut n_events = 0u64;

        for rec in records {
            // Synthesize timer ticks the live loop would have fired.
            if let (Some(nf), Some(ns)) = (next_fast, next_sec) {
                let (mut nf, mut ns) = (nf, ns);
                while nf.min(ns) <= rec.ts {
                    if nf <= ns {
                        self.sim_now = Some(nf);
                        self.on_fast_tick();
                        nf += 0.1;
                    } else {
                        self.sim_now = Some(ns);
                        self.on_second();
                        ns += 1.0;
                    }
                }
                next_fast = Some(nf);
                next_sec = Some(ns);
            }
            self.sim_now = Some(rec.ts);

            match rec.kind {
                RecordKind::Window {
                    market,
                    open_price,
                    open_ts,
                    annual_vol,
                } => {
                    if let Some(prev) = self.market.clone() {
                        self.settle_window(&prev);
                    }
                    if annual_vol > 0.0 {
                        self.fair.seed_historical_vol(annual_vol);
                    }
                    if open_price > 0.0 {
                        self.fair.set_open_price(open_price, open_ts);
                    }
                    self.start_window(market);
                    next_fast = Some(rec.ts);
                    next_sec = Some(rec.ts);
                }
                RecordKind::Ev(ev) => {
                    // Own-fill events are regenerated by the DryRun exec.
                    if matches!(ev, Event::UserTrade { .. } | Event::OrderAck { .. }) {
                        continue;
                    }
                    if let Some(m) = self.market.clone() {
                        if rec.ts >= m.end_ts {
                            self.settle_window(&m);
                            self.market = None;
                        }
                    }
                    n_events += 1;
                    self.on_event(ev);
                }
            }
        }
        if let Some(m) = self.market.clone() {
            self.settle_window(&m);
        }
        tracing::info!("replay complete: {n_events} events from {}", path.display());
        Ok(())
    }
}
